title: Kathleen Sapien # your name (or website title) here
logo: "/images/kat_sapien.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A California native, journalist and technical writer living in Minneapolis, Minn.
  <br><br>
  In my spare time, I enjoy foodie adventures and exploring what the Twin Cities have to offer.
  <br><br>
  <a href="/pdf/sample_presentation.pdf">Resume</a>
  <br><br>
  <b>Connect with me:</b>
  <br><br>
  <a href="https://www.linkedin.com/in/katcsapien/">LinkedIn</a>
  <br><br>
  <a href="https://twitter.com/@katcsapien">Twitter</a>
  <br><br>
  <a href="https://www.instagram.com/katsandy92/">Instagram</a>
  <br><br>
  <a href="mailto:kathleen.sapien3@gmail.com">Email</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
